### ISSUE TITLE
我有问题

### ISSUE THREAD

**Issue by chenjjjjuu** [fuyongXu/pytorch_image_classifier_tutorial#1]
可以加微信私聊吗？我想吧CBAM模块加入到其他的目标检测项目中，但是有点摸不着头脑。有偿

**Comment by fuyongXu** [comment]
不好意思啊，这段时间忙着写论文。




| |
vector_xu
|
|
邮箱：vector_xu@163.com
|

Signature is customized by Netease Mail Master

在2020年03月16日 20:53，chenjjjjuu 写道：

Closed #1.

**Comment by chenjjjjuu** [comment]
没事，等你忙完了这段时间可以回复我吗，我想请教你一下。



---原始邮件---
发件人: "Xu_fuyong"<notifications@github.com&gt;
发送时间: 2020年3月16日(周一) 晚上10:12
收件人: "fuyongXu/deeplearning_models_classifier_tutorial"<deeplearning_models_classifier_tutorial@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"chenjjjjuu"<1540358700@qq.com&gt;;
主题: Re: [fuyongXu/deeplearning_models_classifier_tutorial] 我有问题 (#1)




 不好意思啊，这段时间忙着写论文。
 
 
 
 
 | |
 vector_xu
 |
 |
 邮箱：vector_xu@163.com
 |
 
 Signature is customized by Netease Mail Master
 
 在2020年03月16日 20:53，chenjjjjuu 写道：
 
 Closed #1.
